### PR TITLE
Refactor k8s_cluster_info to use new module_utils code

### PR DESCRIPTION
**Pull request by gravesm**
##### SUMMARY

Refactor k8s_cluster_info to use new module_utils code

##### COMPONENT NAME

k8s_cluster_info

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by alinabuzachis — APPROVED** [review]

**Comment by gravesm** [comment]
recheck

**Comment by Akasurde** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by Akasurde** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Pull request merged**
