### PR TITLE
turn network-ee-sanity-tests non-voting

### PR DESCRIPTION
**Pull request by goneri**

### CODE REVIEW

**Comment by gravesm** [comment]
Didn't even know this was possible

**Comment by goneri** [comment]
> Didn't even know this was possible

I still need to find the write syntax :-).

**Comment by goneri** [comment]
fyi, the documentation is here: https://zuul-ci.org/docs/zuul/3.10.1/user/config.html#configuration-items

**Review by gravesm — APPROVED** [review]

**Comment by gravesm** [comment]
recheck

**Pull request merged**
