### PR TITLE
[DNM] Disable GitHub Workflow

### PR DESCRIPTION
**Pull request by Akasurde**
Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/998
Depends-On: https://github.com/ansible-collections/kubernetes.core/pull/178
Depends-On: https://github.com/ansible-collections/kubernetes.core/pull/177

##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
.github/workflows/ci.yml

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by Akasurde** [comment]
recheck

**Pull request closed without merging**
