### PR TITLE
Port changes from main to refactored branch

### PR DESCRIPTION
**Pull request by gravesm**
Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/1563

##### SUMMARY

This PR contains several commits that complete the rebase of the 2.x-refactor branch onto main. Most of the changes here had to be manually backported after rebasing as the original changes were to code that will be deprecated. In addition, rather than trying to manually sort out conflicts and changes to the sanity ignores, I rewrote the `refresh_ignore_files` script to fully automate the management of ignore files. Previously, these files were both manually edited and auto-generated. This should no longer be the case, and these files should never be manually edited going forward.

For the purposes of reviewing and history, I kept all changes in separate commits tied to the original commit being backported.

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by gravesm** [comment]
check on-demand

**Comment by gravesm** [comment]
check ondemand

**Comment by gravesm** [comment]
recheck

**Review by jillr — APPROVED** [review]
With the understanding that I didn't work on the refactor so I'm looking at this completely in isolation, this seems reasonable to me.

**Pull request merged**
