### PR TITLE
Documentation update for kubernetes.core.helm

### LINKED ISSUE #316: Document usage of kubernetes.core.helm to do a `helm repo update`
##### SUMMARY

The documentation for `kubernetes.core.helm`, option `update_repo_cache` says the following (emphasis mine): 
```
- update_repo_cache
        Run `helm repo update' before the operation. Can be run as part of the
        package installation **or as a separate step**.
        [Default: False]
        type: bool
```
However, how to update the repo cache as a separate step is not obvious. One has to do ["lots of gymnastics"](156#issuecomment-990682141) :
```
  - name: helm repo update
    kubernetes.core.helm:
      state: absent
      binary_path: /usr/local/bin/helm3
      release_name: dummy # tricks needed to refresh in separate step
      release_namespace: kube-system
      update_repo_cache: true
```
This workaround should be documented, or maybe a more explicit way could be added ?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

kubernetes.core.helm

##### ANSIBLE VERSION

```
ansible [core 2.12.1]
  config file = /home/max/dev_com/kubespray/ansible.cfg
  configured module search path = ['/home/max/dev_com/kubespray/library']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/max/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

### PR DESCRIPTION
**Pull request by VannTen**
Clarify usage of the module for doing `helm repo update` only.

I used collection_prep_add_docs as explained in CONTRIBUTING.md, not sure if
that's correct ?

Fixes #316  
@Akasurde

### CODE REVIEW

**Review by Akasurde — COMMENTED** [review]
LGTM, @abikouo @gravesm What do you think?

**Comment by gravesm** [comment]
If there is a desire to update the repo cache in a separate step, I would rather see us provide more explicit functionality to do that, probably in the `helm_repository` module. This workaround is potentially problematic because it relies on choosing a release name that isn't in use.

**Comment by VannTen** [comment]
On Mon, Jan 10, 2022 at 07:08:32AM -0800, Mike Graves wrote:
> If there is a desire to update the repo cache in a separate step, I
> would rather see us provide more explicit functionality to do that,
> probably in the `helm_repository` module. This workaround is
> potentially problematic because it relies on choosing a release name
> that isn't in use.

I agree. However, right now, the documentation hints that it is possible
but do not specify how, which is confusing. Documenting the workaround
until a specific option is provided will avoid users wasting time
searching for how to use the documented feature.

**Comment by Akasurde** [comment]
recheck

**Comment by Akasurde** [comment]
@gravesm Updating repo using `helm_repository` will also be the same since `repo_url` and `repo_name` will be required.

For now, I think this is OK.

**Review by gravesm — APPROVED** [review]
Sure, that's fine.

**Pull request merged**
