### PR TITLE
allow turbo mode, but disabled by default

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible-collections/cloud.common/pull/73

Expose a new parameter called enable_session_cache to enable the
feature.

### CODE REVIEW

**Comment by gravesm** [comment]
This option will need to be added to most of the k8s_* modules.

**Comment by goneri** [comment]
> This option will need to be added to most of the k8s_* modules.

Yes, I'm doing my test with just k8s for now. @gravesm  How do you feel with this design?

**Comment by gravesm** [comment]
I think an env var or a global ansible setting would be a better solution, but I understand those will be much more difficult to implement. I'll do some testing on my own end to see how this works.

**Comment by goneri** [comment]
Superseded by https://github.com/ansible-collections/kubernetes.core/pull/169

**Pull request closed without merging**
