### PR TITLE
[backport/2.2] Add integration test to check handling of module_defaults

### PR DESCRIPTION
**Pull request by gravesm**
Add integration test to check handling of module_defaults

SUMMARY

Add integration test to make sure that module_defaults are handled correctly in tasks.
Related to #126.

ISSUE TYPE

Bugfix Pull Request

Reviewed-by: Mike Graves <mgraves@redhat.com>
Reviewed-by: None <None>
(cherry picked from commit 79699ba4296b378caa5fa61167b5b9e14d27ea9e)

### CODE REVIEW

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Review by abikouo — APPROVED** [review]

**Pull request merged**
