### PR TITLE
Refactor k8s_exec to use new module_utils code

### PR DESCRIPTION
**Pull request by alinabuzachis**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1340

##### SUMMARY

Refactor k8s_exec to use new module_utils code

Requires https://github.com/ansible-collections/kubernetes.core/pull/329

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

k8s_exec

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Comment by Akasurde** [comment]
```
'K8SDynamicClient' object has no attribute 'client_side_validation'"
```

**Comment by alinabuzachis** [comment]
recheck

**Review by gravesm — APPROVED** [review]

**Comment by Akasurde** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by Akasurde** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
@gravesm I guess this one can be merged now, right?

**Comment by gravesm** [comment]
Yes! I'm just going to manually squash/merge this one, rather than trying to get it to gate.

**Pull request merged**
