### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by pierreozoux**
replaces https://github.com/ansible-collections/kubernetes.core/pull/799

### CODE REVIEW

**Comment by yurnov** [comment]
Hi @pierreozoux,

could you please add a changelog fragment?

**Comment by pierreozoux** [comment]
@yurnov ok like this?

**Comment by gravesm** [comment]
Docs changes do not actually need a change log. If you want to provide one, it should be `trivial` instead of `bugfixes`.

**Review by abikouo — APPROVED** [review]

**Comment by pierreozoux** [comment]
\o/

:pray: 

danke!

**Pull request merged**
