### PR TITLE
Show diff for black check

### PR DESCRIPTION
**Pull request by gravesm**
##### SUMMARY

Show diff for black check

This will make it easier to see from the CI logs what the actual problem
is.

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Review by abikouo — APPROVED** [review]
@gravesm could you please apply the same modification on line 51 ?
Thanks

**Review by Akasurde — APPROVED** [review]

**Review by alinabuzachis — APPROVED** [review]

**Pull request merged**
