### PR TITLE
molecule gc.yml - fix sporadic fail

### PR DESCRIPTION
**Pull request by abikouo**
##### SUMMARY

Improve https://github.com/ansible-collections/kubernetes.core/pull/132

### CODE REVIEW

**Review by gravesm — COMMENTED** [review]
Does the `until` fix not work?

**Comment by Akasurde** [comment]
> Does the `until` fix not work?

I guess no. Since it is not able to find `status` in `resource[0]`

**Comment by abikouo** [comment]
> > Does the `until` fix not work?
> 
> I guess no. Since it is not able to find `status` in `resource[0]`

indeed seems not enough, and we cannot add a wait condition for Job resource type as the API does not return information on Pods statuses.

**Comment by Akasurde** [comment]
@abikouo Do you know any other predictive way by which we can remove the hardcoded sleep value?

**Comment by Akasurde** [comment]
Make sense to me.

**Review by gravesm — APPROVED** [review]
I will be glad to have this fixed. :tada:

**Pull request merged**
