### PR TITLE
helm_template: change order of values_release and values_files

### PR DESCRIPTION
**Pull request by cvstebut**
##### SUMMARY

This fix aligns precedence of release_values and values_files in kubernetes.core.helm_template with the one in kubernetes.core.helm. 
The values in release_values are now processed last, thus with highest precedence.
This allows overwriting of values in values_files with the values presented in release_values.

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by Akasurde — COMMENTED** [review]
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example. Also, could you please add a test for this change?

**Comment by Akasurde** [comment]
recheck

**Comment by cvstebut** [comment]
Sorry it took a little while for the changelog fragment and test. For a newbie, changing the order of some lines is easy; the necessary test took a little bit more research.

I have included a unit test checking the order of the parameters in the "helm template ..." command string generated by the helm_template module.

In my view, the unit test should be enough in this case, as no module parameters were changed.

Not sure I have put it in the "correct" place, as it seems to be the first unit test for modules.

Also not sure, if it is ok to base the test on an "internal" function of the module; but this does allow to test the only relevant output of the module. An alternative would be to extract the generated command by defining a MockedModule including the run_command and extracting the command parameter. (similar to tests/unit/module_units/htest_helm.py)
Please advise.

I am thinking about adding other parameters to the module (e.g. release_name) (see #313) , but first I will  start looking into how to test module parameters and generated docs.

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
@cvstebut Thanks for the changelog and the tests. We would typically add a test for this in the integration test suite here: https://github.com/ansible-collections/kubernetes.core/tree/main/molecule/default/roles/helm/tasks, but the unit test works, as well.

**Comment by cvstebut** [comment]
recheck

**Comment by Akasurde** [comment]
recheck

**Comment by Akasurde** [comment]
@cvstebut Due to a change in CI I am closing this PR and reopening it as https://github.com/ansible-collections/kubernetes.core/pull/373. Thanks for the contribution.

**Pull request closed without merging**
