### PR TITLE
Release 2.4.0

### PR DESCRIPTION
**Pull request by abikouo**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1758
Release `2.4.0`

### CODE REVIEW

**Comment by abikouo** [comment]
check ondemand

**Comment by abikouo** [comment]
check ondemand

**Comment by abikouo** [comment]
check ondemand

**Comment by abikouo** [comment]
check ondemand

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
check ondemand

**Comment by abikouo** [comment]
recheck

**Review by gravesm — APPROVED** [review]

**Pull request merged**
