### PR TITLE
[backport/2.3] Upgrade black version (#424)

### PR DESCRIPTION
**Pull request by gravesm**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1515

Upgrade black version

SUMMARY

Move off of beta version of black and pin to current calendar year
version.
The only manual changes here are to tox.ini. Everything else is from running the new version of black.

ISSUE TYPE

COMPONENT NAME

ADDITIONAL INFORMATION

Reviewed-by: Abhijeet Kasurde <None>
(cherry picked from commit 7c71436f3b3e3fb51e1ce78177a885b7293007c4)

### CODE REVIEW

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by gravesm** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Pull request merged**
