### PR TITLE
k8scopy: rely on existing kubectl binary

### PR DESCRIPTION
**Pull request by Akasurde**
Depends-On: https://github.com/ansible-collections/kubernetes.core/pull/367

##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
molecule/default/roles/k8scopy/defaults/main.yml
molecule/default/roles/k8scopy/tasks/main.yml
molecule/default/roles/k8scopy/tasks/test_copy_directory.yml
molecule/default/roles/k8scopy/tasks/test_copy_file.yml
molecule/default/roles/k8scopy/tasks/test_copy_large_file.yml
molecule/default/roles/k8scopy/tasks/test_multi_container_pod.yml

### CODE REVIEW

**Comment by abikouo** [comment]
I would rather prefer keeping the existing and just check if there is a version installed

**Comment by abikouo** [comment]
I would rather prefer doing something like 

```
- name: check if script is existing
  command: "command -v kubectl"
  register: result
  ignore_errors: true

- name: set path when existing
  set_fact:
     kubectl_path: "{{ result.stdout }}"
  when: result.rc == 0

- block: 
   (...) Download kubectl here

  when: result.rc != 0
```

This will allow running the test on environemnts where the kubectl is not installed.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
> I would rather prefer doing something like
> 
> ```
> - name: check if script is existing
>   command: "command -v kubectl"
>   register: result
>   ignore_errors: true
> 
> - name: set path when existing
>   set_fact:
>      kubectl_path: "{{ result.stdout }}"
>   when: result.rc == 0
> 
> - block: 
>    (...) Download kubectl here
> 
>   when: result.rc != 0
> ```
> 
> This will allow running the test on environemnts where the kubectl is not installed.

I like @Akasurde approach because it simplify the structure of the tests and the new requirement is really reasonable IMO.

**Comment by goneri** [comment]
For the record, I also pushed a similar change here: https://github.com/ansible/ansible-zuul-jobs/commit/ebaf966fe782f0f47099cb84229f740e31b4421a

**Comment by Akasurde** [comment]
mergeit

**Pull request closed without merging**
