### PR TITLE
Add unit and sanity tests to GHA

### PR DESCRIPTION
**Pull request by GomathiselviS**
##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by abikouo** [comment]
How do you deal with a non-voting job like sanity devel that is failing on zuul and is supposed to do the same on GHA?

**Comment by abikouo** [comment]
please consider this new feature https://github.com/ansible-network/github_actions/pull/80 to deal with non-voting workflow

**Comment by Qalthos** [comment]
So I will point out that sanity devel is already non-blocking, as evidenced by all_green succeeding in this very PR. The linked actions PR is to expand that beyond devel (say, milestone)

**Pull request merged**
