### PR TITLE
Align `helmdiff_check` behavior with the `deploy` function

### LINKED ISSUE #638: Helm diff does not use set_values
hi..
Thank you for this great collection!
I encountered what I consider to be a bug while deploying Linkerd.

##### SUMMARY

When deploy helm chart with kubernetes.core.helm, the helm diff plugin will not use any `set_values`.
This prevent deployment even if not using --diff in terraform.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.helm .

##### ANSIBLE VERSION

```paste below
(venv) ➜  kubernetes git:(master) ✗ ansible-playbook --version                                                                    
ansible-playbook [core 2.14.5]
  config file = None
  configured module search path = ['/Users/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXX/Gitlab/ansible/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/XXX/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/XXX/Gitlab/ansible/venv/bin/ansible-playbook
  python version = 3.10.12 (main, Jun 15 2023, 07:49:25) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/pierrepaci/Gitlab/ansible/venv/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/XXX/Gitlab/ansible/venv/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0  

# /Users/XXX/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0 
```

##### STEPS TO REPRODUCE

You can use the following to see that helm diff doesn't pass the set values

```yaml
- name: Install Linkerd-control-plane chart
  kubernetes.core.helm:
    context: "{{ kubernetes_context }}"
    name: linkerd-control-plane
    chart_ref: linkerd-control-plane
    release_namespace: "{{ linkerd_namespace }}"
    chart_repo_url: https://helm.linkerd.io/stable
    chart_version: "{{ linkerd_control_plan_chart_version }}"
    wait: true
    wait_timeout: 300s
    set_values:
      # Trust anchor
      - value: "identity.issuer.scheme=kubernetes.io/tls"
        value_type: string
      - value: "identityTrustAnchorsPEM={{temp_dir.path}}/anchor-ca.crt"
        value_type: file
      # Webhook
      - value: "policyValidator.externalSecret=true"
        value_type: string
      - value: "policyValidator.caBundle={{temp_dir.path}}/webhook-ca.crt"
        value_type: file
      - value: "proxyInjector.externalSecret=true"
        value_type: string
      - value: "proxyInjector.caBundle={{temp_dir.path}}/webhook-ca.crt"
        value_type: file
      - value: "profileValidator.externalSecret=true"
        value_type: string
      - value: "profileValidator.caBundle={{temp_dir.path}}/webhook-ca.crt"
        value_type: file
    values: "{{ values_combined }}"
```

##### EXPECTED RESULTS

Being able to run a second time my playbook. The first deployment work since diff doesn't see the values.

##### ACTUAL RESULTS

```paste below
TASK [linkerd : Install Linkerd-control-plane chart] *****************************************************************************************
fatal: [XXX]: FAILED! => {"changed": false, "command": "/opt/homebrew/bin/helm diff upgrade linkerd-control-plane linkerd-control-plane --repo=https://helm.linkerd.io/stable --version=1.12.5 --reset-values -f=/var/folders/nj/_rfnr_wj13l5k7frc5bkfj_w0000gn/T/tmpqzl3msnd.yml", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: Failed to render chart: exit status 1: Error: execution error at (linkerd-control-plane/templates/identity.yaml:20:21): Please provide the identity issuer certificate\n\nUse --debug flag to render out invalid YAML\n\nError: plugin \"diff\" exited with error\n", "stderr": "Error: Failed to render chart: exit status 1: Error: execution error at (linkerd-control-plane/templates/identity.yaml:20:21): Please provide the identity issuer certificate\n\nUse --debug flag to render out invalid YAML\n\nError: plugin \"diff\" exited with error\n", "stderr_lines": ["Error: Failed to render chart: exit status 1: Error: execution error at (linkerd-control-plane/templates/identity.yaml:20:21): Please provide the identity issuer certificate", "", "Use --debug flag to render out invalid YAML", "", "Error: plugin \"diff\" exited with error"], "stdout": "", "stdout_lines": []}
```

##### WORKAROUND

Settings my values as `values` does work but I would still consider this a bug since `set_values` should be supported.

### LINKED ISSUE #669: Installed Helm diff plugin may break deploy
##### SUMMARY
When you have the Helm Diff plugin installed, the `kubernetes.core.helm` module run the `diff ` command before deploy. But, the command line generation logic works different and put generated yaml of a `[release_]values` dict to the first place before `values_files`, that means that these generated values become hidden.

This is quite similar to the https://github.com/ansible-collections/kubernetes.core/issues/638 issue.
I'm going to raise a PR.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.helm

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.11]
```

##### COLLECTION VERSION

```paste below
kubernetes.core 3.0.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

doesn't matter

##### STEPS TO REPRODUCE

```yaml
 kubernetes.core.helm:
    atomic: true
    name: "{{ helm_release_name }}"
    chart_ref: "{{ playbook_dir + '/../helm/my_app/' }}"
    namespace: "{{ namespace }}"
    wait: true
    state: present
    force: true
    values_files: "{{ values_files | select | list }}"
    release_values:
      region: "hidden_one"
  vars:
    values_files:
      - "{{ playbook_dir }}/../helm/my_app/values-commons.yaml"
```
where `values-commons.yaml` is:
```yaml
region: default
```

##### EXPECTED RESULTS

The result `region:` value rendered to `hidden_one`

##### ACTUAL RESULTS

The result `region` value for `helm diff upgrade` will be `default` instead of `hidden_one`

### PR DESCRIPTION
**Pull request by psmolkin**
##### SUMMARY
Align `helmdiff_check` behavior with the `deploy` function
- Fixes #638
   `helmdiff_check` respects `set_values` parameter
- Fixes #669
   `helmdiff_check` command line parameters sequence aligned to the `deploy` function

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
kubernetes.core.helm

### CODE REVIEW

**Comment by psmolkin** [comment]
recheck

**Comment by psmolkin** [comment]
recheck

**Comment by psmolkin** [comment]
Hello @abikouo @alinabuzachis @gravesm,
I found that the [helm_kubeconfig](https://github.com/ansible-collections/kubernetes.core/blob/main/tests/integration/targets/helm_kubeconfig/tasks/tests_helm_auth.yml) integration test fails due to incompatibility between the latest version of `bitnami/rabbitmq` chart and outdated Helm binaries (<=3.10.0). The default version is set to [3.7.0](https://github.com/ansible-collections/kubernetes.core/blob/main/tests/integration/targets/install_helm/defaults/main.yml#L2)

**Comment by gravesm** [comment]
Thanks. Would you mind bumping the version in your PR?

**Pull request merged**
