### PR TITLE
fix(Collection's util resource discovery fails when complex subresources present #659)

### PR DESCRIPTION
**Pull request by bastienbosser**
##### SUMMARY
Hi,
We have the same problem and on our side we have fixed the code, specifying to the split to do it only on the first /.
```
resource, name = subresource["name"].split("/", 1)
```
It seems more logical to add this control, since the current code doesn't support more than two elements

##### ISSUE TYPE

- Bugfix Pull Request #659 

##### COMPONENT NAME

discovery.py

### CODE REVIEW

**Comment by gravesm** [comment]
@bastienbosser Thanks for your PR. Could you include [a changelog](https://docs.ansible.com/ansible/latest/community/development_process.html#community-changelogs) please?

**Comment by bastienbosser** [comment]
Hello, 
I've added a changelog fragment. Do you think the PR will be merged soon? If so, will a new release be created soon?
Regards,

**Review by alinabuzachis — APPROVED** [review]

**Comment by abikouo** [comment]
@bastienbosser you need to rebase your branch with the `main` branch in order to fix the integration tests issue.
The corresponding targets were fixed into #670 
Thanks

**Review by gravesm — APPROVED** [review]

**Comment by gravesm** [comment]
regate

**Pull request merged**
