### PR TITLE
DNM - Enable SF for collection

### PR DESCRIPTION
**Pull request by abikouo**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1383

### CODE REVIEW

**Comment by goneri** [comment]
sorry, You cannot Depends-On this change because it's from a "trusted" repository.

**Comment by abikouo** [comment]
> sorry, You cannot Depends-On this change because it's from a "trusted" repository.

yes I just remembered right after I did it 
Thanks

**Comment by goneri** [comment]
> > sorry, You cannot Depends-On this change because it's from a "trusted" repository.
> 
> yes I just remembered right after I did it Thanks

eheh, I could have wrote this :-)

**Comment by gravesm** [comment]
Can we close this one, or do we still need it?

**Pull request closed without merging**
